import { Link } from 'react-router-dom';
import { 
  SparklesIcon, 
  MapIcon, 
  ClockIcon, 
  GlobeAltIcon,
  CheckCircleIcon 
} from '@heroicons/react/24/outline';
import Navbar from '@components/common/Navbar';
import Footer from '@components/common/Footer';
import { LOGO_URL } from '@utils/constants';
import { motion } from 'framer-motion';

const Landing = () => {
  const features = [
    {
      icon: SparklesIcon,
      title: 'AI-Powered Planning',
      description: 'Get personalized itineraries generated by advanced AI technology.',
    },
    {
      icon: MapIcon,
      title: 'Detailed Itineraries',
      description: 'Day-by-day plans with activities, restaurants, and recommendations.',
    },
    {
      icon: ClockIcon,
      title: 'Save Time',
      description: 'No more hours of research. Get your plan in minutes.',
    },
    {
      icon: GlobeAltIcon,
      title: 'Any Destination',
      description: 'Plan trips to anywhere in the world with local insights.',
    },
  ];

  const benefits = [
    'Personalized day-by-day itineraries',
    'Budget-conscious recommendations',
    'Activity suggestions based on your preferences',
    'Editable and customizable plans',
    'Save and access trips anytime',
  ];

  return (
    <div className="min-h-screen flex flex-col bg-white">
      <Navbar />

      {/* Hero Section */}
      <section className="flex-1 flex items-center justify-center px-4 py-12 md:py-20 bg-gradient-to-br from-primary-50 via-blue-50 to-indigo-50">
        <div className="max-w-6xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold text-dark-900 mb-4 md:mb-6 leading-tight">
              Plan Your Perfect Trip
              <br />
              <span className="text-primary-600">With AI</span>
            </h1>
            <p className="text-base sm:text-lg md:text-xl text-gray-600 mb-6 md:mb-8 max-w-3xl mx-auto px-4">
              Get personalized travel itineraries in minutes. Just tell us where you want to go, 
              and our AI will create the perfect plan for you.
            </p>
            <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center px-4">
              <Link to="/signup" className="btn-primary text-sm sm:text-base px-6 sm:px-8 py-3 sm:py-4 w-full sm:w-auto">
                Get Started Free
              </Link>
              <Link to="/login" className="btn-secondary text-sm sm:text-base px-6 sm:px-8 py-3 sm:py-4 w-full sm:w-auto">
                Login
              </Link>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-12 md:py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4">
          <div className="text-center mb-10 md:mb-16">
            <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-dark-900 mb-3 md:mb-4">
              Why Choose Our Platform?
            </h2>
            <p className="text-sm sm:text-base md:text-lg text-gray-600">
              Smart travel planning powered by artificial intelligence
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-6 md:gap-8">
            {features.map((feature, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                viewport={{ once: true }}
                className="card text-center"
              >
                <div className="h-10 w-10 sm:h-12 sm:w-12 rounded-xl bg-primary-50 text-primary-600 flex items-center justify-center mx-auto mb-3 sm:mb-4">
                  <feature.icon className="h-5 w-5 sm:h-6 sm:w-6" />
                </div>
                <h3 className="text-base sm:text-lg md:text-xl font-semibold text-dark-900 mb-2">
                  {feature.title}
                </h3>
                <p className="text-xs sm:text-sm text-gray-600">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Benefits Section - WITH LOGO */}
      <section className="py-12 md:py-20 bg-gray-50">
        <div className="max-w-5xl mx-auto px-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12 items-center">
            <div>
              <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-dark-900 mb-4 md:mb-6">
                Everything You Need for the Perfect Trip
              </h2>
              <ul className="space-y-3 sm:space-y-4">
                {benefits.map((benefit, index) => (
                  <li key={index} className="flex items-start">
                    <CheckCircleIcon className="h-5 w-5 sm:h-6 sm:w-6 text-green-600 mr-2 sm:mr-3 flex-shrink-0 mt-0.5" />
                    <span className="text-sm sm:text-base md:text-lg text-gray-700">{benefit}</span>
                  </li>
                ))}
              </ul>
              <Link to="/signup" className="btn-primary mt-6 md:mt-8 inline-flex text-sm sm:text-base">
                Start Planning Now
              </Link>
            </div>
            {/* ✅ ADDED LOGO IMAGE */}
            <div className="flex items-center justify-center">
              <div className="relative">
                <div className="absolute inset-0 bg-primary-100 rounded-full blur-3xl opacity-30"></div>
                <img 
                  src={LOGO_URL} 
                  alt="Travel Planner Logo" 
                  className="relative w-48 h-48 sm:w-64 sm:h-64 md:w-80 md:h-80 object-contain drop-shadow-2xl"
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-12 md:py-20 bg-gradient-to-r from-primary-600 to-primary-700">
        <div className="max-w-4xl mx-auto text-center px-4">
          <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-white mb-4 md:mb-6">
            Ready to Start Your Adventure?
          </h2>
          <p className="text-base sm:text-lg md:text-xl text-primary-100 mb-6 md:mb-8">
            Join thousands of travelers who plan smarter with AI
          </p>
          <Link
            to="/signup"
            className="inline-flex items-center px-6 sm:px-8 py-3 sm:py-4 bg-white text-primary-600 rounded-xl font-semibold text-sm sm:text-base md:text-lg hover:bg-primary-50 transition-colors shadow-lg"
          >
            Create Your Free Account
          </Link>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default Landing;
